### PR TITLE
notify changes to zoom and maptype

### PR DESCRIPTION
**Pull request by jshortall**
This PR adds notification to the zoom and mapType properties. This is useful for saving map state in the url or localstorage so the map is unchanged when the user refreshes.

Hope its helpful and you can accept!

Thanks

Jason

### CODE REVIEW

**Comment by ebidel** [comment]
I'm not opposed to making these 2-way, but is it common? Instead of opting everyone into 2-way binding for these properties, couldn't you construct the URL correctly from the relevant properties your app is interested in?

**Comment by jshortall** [comment]
I could set up google listeners on my page like this, but of course it's not declarative:
```javascript
google.maps.event.addListener(this.$.map.map, 'zoom_changed', function() {
     this.zoom = this.$.map.map.getZoom();
}.bind(this));
google.maps.event.addListener(this.$.map.map, 'maptypeid_changed', function() {
     this.mapType = this.$.map.map.getMapTypeId();
}.bind(this));
```
It seems common to want the zoom and mapType to be observable for an interactive map so that your state isn't lost, similar to this - "https://www.google.com/maps/place/San+Francisco,+CA/@37.7577,-122.4376,13z/". Honestly I was surprised when those attributes didn't act like the latitude and longitude because to me they seemed like the same type of properties (map state).

I'm not picturing scenarios where its a bad thing to have them bind. Could you give me some examples to balance my opinion?

**Comment by atotic** [comment]
Seems sensible, and consistent with the way we handle lat/long.

This kind of code gets tricky because now you have a loop:
setting zoom on element calls `_zoomChanged` which calls `map.setZoom`, which triggers `zoom_changed` event, which sets `this.zoom` which triggers `_zoomChanged`... We've had problems where number conversions for caused several loops before everything settled. Can you test and make sure that setting new zoom on an element (such as 9.33333) does not cause a loop?

**Comment by jshortall** [comment]
When the zoom is changed, there is a 3 step cycle. 
1. The google "zoom_changed" event listener runs.
2. The polymer _zoomChanged listener runs
3. The google "zoom_changed" event listener runs once more.

This happens the same way for whole numbers and repeating numbers like 9.33333. If we change line 530 in _zoomChanged to be:
```javascript
if (this.zoom != this.map.getZoom()) {
  this.map.setZoom(Number(this.zoom));
}
```
I believe that would prevent any looping (it does in my testing). Not sure how to make that edit - a new pull request?

Also, as a side note... There is no map data at .3333 zoom levels so that shouldn't generally be an issue... except that there is some sort of alien planet at and around:
40.21313975507575/-77.13621261124197/16.33333333/hybrid
...not sure what that is about!

**Comment by jshortall** [comment]
Woops. It looks like a new push to my repository includes it in this pull request. Sorry, I am new to public repositories.

I have also updated the poly (-line and -gon) components created by DracoNoir (https://github.com/GoogleWebComponents/google-map/pull/101) to support Polymer 1.0 and they are working nicely.

I intended to submit these as two separate pull requests. Let me know if you'd like me to close these and re-submit.

**Comment by atotic** [comment]
Thanks for trying this out. Lets add the loop prevention code to your pull request.

You'll have to create another pull request. All checkins to the branch that originated the request are added to the pull request. This request now also contains your `creates components for map polylines and polygons` checkin, which is a separate feature.

@ebidel want to confirm with you that we want this patch before he does all the work.

**Comment by ebidel** [comment]
I'm fine with it. Just double check this actually creates a cycle. I know in the 0.5 days, Polymer would
settle to a value, meaning this would not create an infinite loop:

    somethingChanged: function() {
      this.something = newVall;
    },

That was with O.o() though. Not sure if the new system acts the same. Regardless, it's safe to have your check in place.

**Comment by brendankenny** [comment]
I cherrypicked @jshortall's first commit from this PR (setting `zoom` and `mapType` to `notify: true`) and made a fresh PR in #203. Let's add it!

**Comment by brendankenny** [comment]
This PR can be closed now since #203 cherrypicked the desired commit.

**Pull request closed without merging**
