### PR TITLE
Adding idle event to list of events

### PR DESCRIPTION
**Pull request by jamierytlewski**
I hope I am doing this right. I tried to follow the standards that were there. 

Besides drag and mouse events, the idle event is helpful as it can fire from a panning (drag) and zoom.

### CODE REVIEW

**Comment by jamierytlewski** [comment]
I signed it!

**Comment by ebidel** [comment]
We need to clear the listener at some point.

**Comment by jamierytlewski** [comment]
I added the clear listener in the same way the others were.

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
