### PR TITLE
Added clientId to support business users

### PR DESCRIPTION
**Pull request by KrisSiegel**
I was having issues getting google-maps-api to work with google-map but since google-map exposes apiKey it should expose clientId to make it easier for business users.

### CODE REVIEW

**Comment by KrisSiegel** [comment]
Done. Signed personally.

**Comment by KrisSiegel** [comment]
Fixed but may need a new PR.

**Comment by KrisSiegel** [comment]
Trying new PR.

**Comment by KrisSiegel** [comment]
Nevermind I can't do that. I'll leave this open and hopefully someone can resolve.

**Comment by ebidel** [comment]
Not sure what happened here. Can you start a fresh PR with the changes?

**Comment by KrisSiegel** [comment]
Hmm *I think* the only way to do a fresh PR is to re-clone and apply my changes. I'll look at it but damn is this a pain just to submit a minor PR.

**Comment by KrisSiegel** [comment]
Closing

**Pull request closed without merging**
