### PR TITLE
Fix for #134, zoomable can't be unset

### PR DESCRIPTION
**Pull request by atotic**
There is no way to set boolean attribute that defaults to true back to false in Polymer
Fix is to rename attribute to notZoomable, and default it to false.

### CODE REVIEW

**Comment by ebidel** [comment]
what about `nozoom`?

**Comment by atotic** [comment]
I like disableZoom.

**Comment by atotic** [comment]
Fixed, PTAL

**Comment by ebidel** [comment]
Ace!

**Pull request merged**
