### PR TITLE
Title does not correspond with google.maps.Marker property

### PR DESCRIPTION
**Pull request by mhuon**
I just changed title to label to match google.maps.Marker property

### CODE REVIEW

**Comment by ebidel** [comment]
Thanks for the PR. This doesn't seem like a worthwhile change. The idea was that we reuse the `title` attr in html and this would also be a breaking change.

**Comment by mhuon** [comment]
Maybe my comment was a little sparse.  Right now if you use marker with title, the title does not show because the google.maps.Marker object doesn't have a title property.  I was spinning my circles trying to figure out why my markers weren't showing the title anymore.

**Comment by ebidel** [comment]
If it had it's own title property it wouldnt work as you expect. Overriding native properties like this have unexpected behaviors. Another reason is that when you mouse over the marker on the map, it's not actually the google-marker element. So it won't show the alt title. We're using using the `title` attr as a convenient (and existing) way to set the marker's title.

**Comment by mhuon** [comment]
I see, thanks for the update.

**Comment by mhuon** [comment]
I'd like to help fix the issue.  Can you point me in the right direction?  Line 407 is throwing me off since you said it's dangerous overriding native properties which makes sense but I can't see where the code is not using native implementations of google maps....I can't seem to figure it out.

**Pull request closed without merging**
