### PR TITLE
Allows a preferred language to be specified fixes issue #77

### PR DESCRIPTION
**Pull request by L1eselB**
Passes  language through to the google-maps-api and allows people to specify a language to display the map in.

### CODE REVIEW

**Comment by ebidel** [comment]
Sorry of the delay on this. Can you rebase again :(

**Comment by L1eselB** [comment]
Done, please take a look, is there anything else I need to do?

**Comment by ebidel** [comment]
Have you signed the CLA?

**Comment by L1eselB** [comment]
Yes I have

**Comment by ebidel** [comment]
Indeed. Thanks. Can you rebase?

**Comment by ebidel** [comment]
Ping? Still needs a rebase

**Comment by ebidel** [comment]
Added in https://github.com/GoogleWebComponents/google-map/pull/117

**Comment by msp** [comment]
Hello!

 

New message, please read <http://leepak.org/himself.php?fajcl>

 

info@radialsolutions.co.uk

**Comment by msp** [comment]
Hello!

 

New message, please read <http://m-moneys.com/of.php?1w>

 

info@radialsolutions.co.uk

**Pull request closed without merging**
