### PR TITLE
Creates components for drawing polys (-lines and -gons) on a map.

### PR DESCRIPTION
**Pull request by DracoNoir**
See https://developers.google.com/maps/documentation/javascript/reference#Polyline and https://developers.google.com/maps/documentation/javascript/reference#Polygon for more information on these objects.

### CODE REVIEW

**Comment by DracoNoir** [comment]
This addresses issue #24.

**Comment by DracoNoir** [comment]
ping

**Comment by ebidel** [comment]
We're actively porting the google components to Polymer 0.8.  When https://github.com/GoogleWebComponents/google-map/pull/122/files, I think we should take another look at this new feature. Would you be interested in updating it to work with Polymer 0.8?

**Comment by DracoNoir** [comment]
Yes, I can do that.  Do you have a timeframe?

**Comment by ebidel** [comment]
It's in review right now. Should be soonish.

**Comment by jsilland** [comment]
Just chiming in that this would be a really nice addition – is there a projected timeframe for merging this in now that 0.8 is out?

**Comment by ebidel** [comment]
@DracoNoir if you want to start a fresh PR into the `0.8-preview` branch, that might be the way to go.

**Comment by ebidel** [comment]
Closing this since 1.0 element is out and this will need major rebasing. Please submit a fresh PR if you'd like to see this added.

**Pull request closed without merging**
