### PR TITLE
Make positionless markers not display but also not throw exception

### LINKED ISSUE #204: Exception when using a google-map-marker without position
In a [recent commit](https://github.com/GoogleWebComponents/google-map/commit/f7b94201870282f512208546e73e507475b02d87) the initailization of the marker position was changed from: `position: new google.maps.LatLng(this.latitude, this.longitude),` to `position: {lat: this.latitude, lng: this.longitude},`. 

This will cause a `Assertion failed: InvalidValueError: setPosition: not a LatLng or LatLngLiteral: in property lat: not a number` when I add a marker without a position to a map: 

```HTML
<google-map latitude="39.91" map="{{map}}" id="mapelement" longitude="116.38" zoom="2" >
        <google-map-marker id="accessionMarker" z-index="9999" ></google-map-marker>
</google-map>
```

### PR DESCRIPTION
**Pull request by brendankenny**
closes #204

### CODE REVIEW

**Comment by ebidel** [comment]
LGTM. Should we do this in other places the literal is set? I think google-map has a few now.

**Comment by brendankenny** [comment]
Hmm, the only other place I see a LatLngLiteral is https://github.com/GoogleWebComponents/google-map/blob/76a5c5348a403fb60109b0208f8892b23f1a7e96/google-map-search.html#L179 and it's sanitized first.

`google-map` has similar cleanup of invalid values in `_updateCenter`

**Comment by ebidel** [comment]
Ayight. Just checking.

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
