### PR TITLE
Use the zoom by parameter

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by ebidel** [comment]
is there a good reason to switch this? I prefer to always use the current value in change handlers.

**Comment by abdonrd** [comment]
I has suggested it because the Polymer docs:
> [Always include dependencies as observer arguments](https://www.polymer-project.org/1.0/docs/devguide/observers#dependencies)

But now... I'm not sure if the recommendation is only for observe multiple properties.

**Comment by ebidel** [comment]
Yea, that's for when you create `observers`. In `observers` you should always use the argument deps/params (rather that `this.varName`) for the reasons mentioned there.

**Comment by abdonrd** [comment]
Then closed! Thanks and sorry @ebidel! 😅

**Pull request closed without merging**
