### PR TITLE
drag events support in google-map-marker element

### PR DESCRIPTION
**Pull request by naderio**

### CODE REVIEW

**Comment by naderio** [comment]
ok, will see

**Comment by naderio** [comment]
it doesn't make sense to recall `_contentChanged` again after `_clickEventsChanged` since the latter only attaches event listeners. anyhow, all 3 click events still work.
otherwise,
* demo is updated to handle marker drag updating the polygon on the map
* a test case that checks for drag events forward setup have been added
* docs now show all elements instead of just `google-map` and `google-map-marker`

**Comment by ebidel** [comment]
LGTM. Just a couple of more nits. Thanks for updating the page and docs.

**Comment by naderio** [comment]
all set

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
