### PR TITLE
[Feat] Adds circle radius to map markers.

### PR DESCRIPTION
**Pull request by kamronbatman**
Adds circle radius to map markers. The following properties are now available through the element.
- accuracy: Radius of the circle, in meters
- circleFillColor: Hex color string
- circleFillOpacity: Number between 0 and 1
- circleStrokeColor: Hex color string
- circleStrokeOpacity: Number between 0 and 1

### CODE REVIEW

**Comment by kamronbatman** [comment]
This is a non-breaking feature with no impact on backward/forward compatibility.

**Comment by kamronbatman** [comment]
Here is an example card I created from the Polymer starter kit using the changes made.

image

**Comment by ebidel** [comment]
Thanks for the PR. I wonder if it would make sense to add this add a behavior to keep the features separated. WDYT?

**Comment by kamronbatman** [comment]
You are definitely right.  Regardless, a google-map-circle element should be implemented. Not sure on implementing binding through an opt-in though. Is there dynamic bindTo implemented somewhere already that we can model the behavior after?

**Comment by ebidel** [comment]
I need to ask the Polymer team. I'm not sure if you can add behaviors after
the prototype is set up.

**Comment by TimvdLippe** [comment]
As far as I am aware, it it not possible to add a behavior post element registration.

**Comment by cwenzelg** [comment]
I would love to see this circle marker come real. is there still interest to add such a marker?

**Comment by kamronbatman** [comment]
Anyone who is interested in this can take over the PR. I don't use polymer or have the right setup to finish this feature.

**Pull request closed without merging**
