### PR TITLE
Add support for iron-icons in icon attribute

### PR DESCRIPTION
**Pull request by klarkc**
Refer: #178

### CODE REVIEW

**Comment by ebidel** [comment]
This seems a bit complex to get svg icon support as the marker. A lot of the methods are specific to configuring `<iron-icon>` and I also don't want to bring into the entire icon set to support a feature not everyone will use.  That increases the overhead of the element.

**Comment by klarkc** [comment]
@ebidel  Yep, I have not figured how to do this without iron-icon dependency :(

**Comment by klarkc** [comment]
@ebidel Maybe a solution is to create another element (like google-map-icon) featuring only iron-icon support, what do you think?

**Comment by ebidel** [comment]
Actually, I like that! It's easier for users to opt-in to that if they want an svg icon.

**Comment by klarkc** [comment]
I am closing this PR for now, because I am working in a new element called [google-map-icon](/klarkc/google-map/tree/google-map-icon) that will extend the behavior of the default google-map-marker. I will PR these modifications in the future.

**Comment by nerdkid93** [comment]
Is that PR ready yet?

**Pull request closed without merging**
