### PR TITLE
google-map-directions and google-map add language attribute("language")

### PR DESCRIPTION
**Pull request by r2fresh**
Maps tried to change the language to another.
But it was an error.
An error has occurred did not contain any language attributes on google-map.html.
So I added the language to google-map.html.
We are soon to become "pull-request".

### CODE REVIEW

**Comment by ebidel** [comment]
Thanks. Can you sign the CLA?

https://github.com/GoogleWebComponents/google-map/pull/85/files also adds the `language` attribute, it it may be abandoned. If you can add the doc strings that PR lands, we can merge this one :)

**Comment by r2fresh** [comment]
I just joined the CLA.
The username is "r2fresh".
OK, thank you.

**Comment by ebidel** [comment]
Great! Can you add the documentation strings?

**Comment by r2fresh** [comment]
Yes! Where is document?

**Comment by ebidel** [comment]
See the other PR: https://github.com/GoogleWebComponents/google-map/pull/85/files#diff-1de9a590f21defa41d706b424e83bb63R601

**Comment by r2fresh** [comment]
I added document string. 
Can you review this again?

**Comment by ebidel** [comment]
:+1:

**Pull request merged**
